from __future__ import annotations


def build_study_schema() -> dict[str, object]:
    backtest_result_schema = {
        "type": "object",
        "required": [
            "trade_count",
            "win_rate",
            "gross_pnl",
            "net_pnl",
            "fee_spend",
            "funding_spend",
            "sharpe",
            "sortino",
            "max_drawdown",
            "equity_curve",
        ],
        "properties": {
            "trade_count": {"type": "integer"},
            "win_rate": {"type": "number"},
            "gross_pnl": {"type": "number"},
            "net_pnl": {"type": "number"},
            "fee_spend": {"type": "number"},
            "funding_spend": {"type": "number"},
            "sharpe": {"type": "number"},
            "sortino": {"type": "number"},
            "max_drawdown": {"type": "number"},
            "equity_curve": {"type": "array", "items": {"type": "number"}},
            "liquidation_events": {"type": "array", "items": {"type": "string"}},
        },
    }

    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": "ProofAlpha Study",
        "type": "object",
        "required": ["run_id", "seed", "snapshot", "incumbent"],
        "properties": {
            "run_id": {"type": "string"},
            "seed": {"type": "integer"},
            "runtime": {
                "type": "object",
                "properties": {
                    "mode": {"type": "string", "enum": ["builtin", "fixture"]},
                    "slippage_bps": {"type": "number"},
                    "latency_bars": {"type": "integer"},
                    "position_side": {"type": "string", "enum": ["long", "short"]},
                    "position_leverage": {"type": "number"},
                    "maintenance_margin_ratio": {"type": "number"},
                    "liquidation_fee_bps": {"type": "number"},
                    "liquidation_mark_price_weight": {"type": "number"},
                    "partial_liquidation_ratio": {"type": "number"},
                    "liquidation_cooldown_bars": {"type": "integer"},
                    "liquidation_step_schedule": {"type": "array", "items": {"type": "number"}},
                    "liquidation_mark_premium_bps": {"type": "number"},
                    "maintenance_margin_schedule": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "required": ["max_leverage", "maintenance_margin_ratio"],
                            "properties": {
                                "max_leverage": {"type": "number"},
                                "maintenance_margin_ratio": {"type": "number"},
                            },
                            "additionalProperties": False,
                        },
                    },
                    "liquidation_fee_schedule": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "required": ["max_leverage", "liquidation_fee_bps"],
                            "properties": {
                                "max_leverage": {"type": "number"},
                                "liquidation_fee_bps": {"type": "number"},
                            },
                            "additionalProperties": False,
                        },
                    },
                    "min_oos_trades": {"type": "integer"},
                    "fail_on_quality_flags": {"type": "boolean"},
                    "bootstrap_samples": {"type": "integer"},
                    "bootstrap_block_size": {"type": "integer"},
                    "bootstrap_spread_multiplier": {"type": "number"},
                    "bootstrap_depth_multiplier": {"type": "number"},
                    "bootstrap_latency_multiplier": {"type": "number"},
                    "holdout_sharpe_floor": {"type": "number"},
                    "holdout_drawdown_cap": {"type": "number"},
                    "scenario_severity_multiplier": {"type": "number"},
                },
                "additionalProperties": False,
            },
            "layer_parameters": {
                "type": "object",
                "additionalProperties": {
                    "type": "object",
                    "properties": {
                        "entry_stride": {"type": "integer"},
                        "mean_threshold_offset": {"type": "number"},
                        "flat_range_threshold": {"type": "number"},
                        "hold_bars": {"type": "integer"},
                        "aggressiveness": {"type": "number"},
                        "strictness": {"type": "number"},
                    },
                    "additionalProperties": {"type": ["number", "integer"]},
                },
            },
            "parameter_grids": {
                "type": "object",
                "additionalProperties": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "object",
                        "required": ["minimum", "maximum", "step"],
                        "properties": {
                            "minimum": {"type": "number"},
                            "maximum": {"type": "number"},
                            "step": {"type": "number"},
                            "excluded_values": {"type": "array", "items": {"type": "number"}},
                        },
                        "additionalProperties": False,
                    },
                },
            },
            "snapshot": {
                "type": "object",
                "required": [
                    "snapshot_id",
                    "symbol",
                    "venue",
                    "timeframe",
                    "candles",
                    "funding_rates",
                    "open_interest",
                    "liquidation_notional",
                    "maker_fee_bps",
                    "taker_fee_bps",
                ],
                "properties": {
                    "snapshot_id": {"type": "string"},
                    "symbol": {"type": "string"},
                    "venue": {"type": "string"},
                    "timeframe": {"type": "string"},
                    "contract_type": {"type": "string"},
                    "candles": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "required": ["timestamp", "open", "high", "low", "close", "volume"],
                            "properties": {
                                "timestamp": {"type": "string", "format": "date-time"},
                                "open": {"type": "number"},
                                "high": {"type": "number"},
                                "low": {"type": "number"},
                                "close": {"type": "number"},
                                "volume": {"type": "number"},
                                "trade_count": {"type": "integer"},
                            },
                        },
                    },
                    "funding_rates": {"type": "array", "items": {"type": "number"}},
                    "open_interest": {"type": "array", "items": {"type": "number"}},
                    "liquidation_notional": {"type": "array", "items": {"type": "number"}},
                    "maker_fee_bps": {"type": "number"},
                    "taker_fee_bps": {"type": "number"},
                    "mark_price": {"type": "array", "items": {"type": "number"}},
                    "index_price": {"type": "array", "items": {"type": "number"}},
                    "next_funding_ts": {"type": "array", "items": {"type": "string", "format": "date-time"}},
                    "open_interest_usd": {"type": "array", "items": {"type": "number"}},
                    "basis_bps": {"type": "array", "items": {"type": "number"}},
                    "liq_long_usd": {"type": "array", "items": {"type": "number"}},
                    "liq_short_usd": {"type": "array", "items": {"type": "number"}},
                    "spread_bps": {"type": "array", "items": {"type": "number"}},
                    "depth_bid_1bp_usd": {"type": "array", "items": {"type": "number"}},
                    "depth_ask_1bp_usd": {"type": "array", "items": {"type": "number"}},
                    "latency_proxy_ms": {"type": "array", "items": {"type": "number"}},
                    "ret_1": {"type": "array", "items": {"type": "number"}},
                    "ret_24": {"type": "array", "items": {"type": "number"}},
                    "rv_24h": {"type": "array", "items": {"type": "number"}},
                    "funding_z": {"type": "array", "items": {"type": "number"}},
                    "d_oi": {"type": "array", "items": {"type": "number"}},
                    "d_oi_z": {"type": "array", "items": {"type": "number"}},
                    "liq_intensity_z": {"type": "array", "items": {"type": "number"}},
                    "vol_regime": {"type": "array", "items": {"type": "string"}},
                    "regime_id": {"type": "array", "items": {"type": "string"}},
                    "regime_probabilities": {"type": "array", "items": {"type": "object"}},
                    "quality_flags": {"type": "array", "items": {"type": "string"}},
                    "venue_profile": {
                        "type": "object",
                        "required": ["venue"],
                        "properties": {
                            "venue": {"type": "string"},
                            "contract_type": {"type": "string"},
                            "quote_currency": {"type": ["string", "null"]},
                            "settlement_currency": {"type": ["string", "null"]},
                            "funding_interval_h": {"type": ["integer", "null"]},
                            "mark_price_source": {"type": "string"},
                            "leverage_tiers": {"type": "array", "items": {"type": "object"}},
                            "maintenance_margin_schedule": {"type": "array", "items": {"type": "object"}},
                            "liquidation_fee_schedule": {"type": "array", "items": {"type": "object"}},
                            "liquidation_style": {"type": "string"},
                            "partial_liquidation_ratio": {"type": "number"},
                            "liquidation_cooldown_bars": {"type": "integer"},
                            "liquidation_mark_price_weight": {"type": "number"},
                            "liquidation_mark_premium_bps": {"type": "number"},
                            "notes": {"type": "array", "items": {"type": "string"}},
                        },
                        "additionalProperties": False,
                    },
                    "quality_report": {
                        "type": "object",
                        "required": ["report_id", "snapshot_id"],
                        "properties": {
                            "report_id": {"type": "string"},
                            "snapshot_id": {"type": "string"},
                            "quality_score": {"type": "number"},
                            "passed": {"type": "boolean"},
                            "issues": {"type": "array", "items": {"type": "string"}},
                            "metrics": {"type": "object"},
                            "source_checks": {"type": "object"},
                            "generated_at": {"type": ["string", "null"]},
                        },
                        "additionalProperties": True,
                    },
                    "provenance": {"type": "object"},
                },
            },
            "incumbent": {
                "type": "object",
                "required": ["backbone"],
                "properties": {
                    "backbone": {"type": "string"},
                    "layers": {"type": "array", "items": {"type": "string"}},
                },
            },
            "directional_layers": {"type": "array", "items": {"type": "string"}},
            "known_good_filters": {"type": "array", "items": {"type": "string"}},
            "custom_filters": {"type": "array", "items": {"type": "string"}},
            "exit_layers": {"type": "array", "items": {"type": "string"}},
            "evaluations": {
                "type": "object",
                "additionalProperties": {
                    "type": "object",
                    "required": ["decision", "train", "oos", "bootstrap"],
                    "properties": {
                        "decision": {"type": "string"},
                        "reasons": {"type": "array", "items": {"type": "string"}},
                        "train": backtest_result_schema,
                        "oos": backtest_result_schema,
                        "bootstrap": {
                            "type": "object",
                            "required": [
                                "sample_count",
                                "median_net_profit",
                                "median_max_drawdown",
                                "worst_case_net_profit",
                                "worst_case_drawdown",
                                "pass_rate",
                            ],
                            "properties": {
                                "sample_count": {"type": "integer"},
                                "median_net_profit": {"type": "number"},
                                "median_max_drawdown": {"type": "number"},
                                "worst_case_net_profit": {"type": "number"},
                                "worst_case_drawdown": {"type": "number"},
                                "pass_rate": {"type": "number"},
                            },
                        },
                    },
                },
            },
            "scenarios": {
                "type": "array",
                "items": {
                    "type": "object",
                    "required": ["name", "severity", "description"],
                    "properties": {
                        "name": {"type": "string"},
                        "severity": {"type": "number"},
                        "description": {"type": "string"},
                        "funding_multiplier": {"type": "number"},
                        "liquidity_penalty_bps": {"type": "number"},
                        "latency_delta_bars": {"type": "integer"},
                        "drawdown_multiplier": {"type": "number"},
                        "mark_premium_bps": {"type": "number"},
                        "index_basis_bps": {"type": "number"},
                        "premium_spike_bars": {"type": "integer"},
                    },
                },
            },
            "scenario_results": {
                "type": "object",
                "additionalProperties": backtest_result_schema,
            },
            "holdout_decision": {
                "type": "object",
                "properties": {
                    "decision": {"type": "string"},
                    "reasons": {"type": "array", "items": {"type": "string"}},
                },
            },
            "advisory_context": {
                "type": "object",
                "properties": {
                    "study_schema_title": {"type": "string"},
                    "layer_catalog": {"type": "object"},
                    "duplicate_baseline_run_id": {"type": ["string", "null"]},
                    "agent_environment": {
                        "type": "object",
                        "properties": {
                            "skills": {"type": "array", "items": {"type": "object"}},
                            "mcp": {"type": "object"},
                            "loop_policy": {"type": "object"},
                        },
                    },
                },
            },
            "advisory_rationale": {
                "type": "object",
                "properties": {
                    "variant": {"type": "string"},
                    "summary": {"type": "string"},
                    "constraints": {"type": "array", "items": {"type": "string"}},
                    "evidence": {"type": "array", "items": {"type": "object"}},
                },
            },
        },
    }
